import { BusRoute, Stop, BusLocation, Arrival, ServiceAlert } from '../types';

export const routes: BusRoute[] = [
  {
    id: 'red',
    name: 'BU Charles River - Medical Campus',
    color: '#CC0000',
    bgColor: '#FFE6E6',
    textColor: '#8B0000',
    description: 'Connects Charles River Campus to Medical Campus',
    active: true,
  },
  {
    id: 'yellow',
    name: 'Fenway',
    color: '#FFA500',
    bgColor: '#FFF5E6',
    textColor: '#CC7A00',
    description: 'Service to Fenway area',
    active: true,
  },
  {
    id: 'green',
    name: 'Comm Ave',
    color: '#00AA00',
    bgColor: '#E6F7E6',
    textColor: '#006600',
    description: 'Commonwealth Avenue route',
    active: true,
  },
  {
    id: 'blue',
    name: 'Future Route',
    color: '#0066CC',
    bgColor: '#E6F2FF',
    textColor: '#004499',
    description: 'Reserved for future expansion',
    active: false,
  },
];

export const stops: Stop[] = [
  {
    id: 'stop-1',
    name: 'Kenmore Station',
    lat: 42.349,
    lng: -71.095,
    routeIds: ['red', 'green'],
    accessible: true,
    transfers: ['Green Line B, C, D'],
  },
  {
    id: 'stop-2',
    name: 'BU Central',
    lat: 42.350,
    lng: -71.106,
    routeIds: ['red', 'green'],
    accessible: true,
    transfers: ['Green Line B'],
  },
  {
    id: 'stop-3',
    name: 'West Campus',
    lat: 42.351,
    lng: -71.118,
    routeIds: ['red'],
    accessible: true,
  },
  {
    id: 'stop-4',
    name: 'Medical Campus',
    lat: 42.336,
    lng: -71.072,
    routeIds: ['red'],
    accessible: true,
  },
  {
    id: 'stop-5',
    name: 'Fenway Park',
    lat: 42.346,
    lng: -71.097,
    routeIds: ['yellow'],
    accessible: true,
    transfers: ['Green Line D'],
  },
  {
    id: 'stop-6',
    name: 'Longwood Medical',
    lat: 42.338,
    lng: -71.100,
    routeIds: ['yellow'],
    accessible: true,
    transfers: ['Green Line E'],
  },
  {
    id: 'stop-7',
    name: 'Warren Towers',
    lat: 42.350,
    lng: -71.104,
    routeIds: ['green'],
    accessible: true,
  },
  {
    id: 'stop-8',
    name: 'Agganis Arena',
    lat: 42.353,
    lng: -71.116,
    routeIds: ['green'],
    accessible: true,
  },
];

export const busLocations: BusLocation[] = [
  {
    id: 'bus-1',
    routeId: 'red',
    lat: 42.349,
    lng: -71.100,
    nextStopId: 'stop-2',
    occupancy: 'medium',
  },
  {
    id: 'bus-2',
    routeId: 'red',
    lat: 42.340,
    lng: -71.080,
    nextStopId: 'stop-4',
    occupancy: 'low',
  },
  {
    id: 'bus-3',
    routeId: 'yellow',
    lat: 42.342,
    lng: -71.098,
    nextStopId: 'stop-6',
    occupancy: 'high',
  },
  {
    id: 'bus-4',
    routeId: 'green',
    lat: 42.351,
    lng: -71.110,
    nextStopId: 'stop-8',
    occupancy: 'medium',
  },
];

export const arrivals: Arrival[] = [
  { stopId: 'stop-1', routeId: 'red', minutes: 2, isLive: true, busId: 'bus-1' },
  { stopId: 'stop-1', routeId: 'red', minutes: 15, isLive: false, busId: 'bus-5' },
  { stopId: 'stop-1', routeId: 'green', minutes: 5, isLive: true, busId: 'bus-4' },
  { stopId: 'stop-2', routeId: 'red', minutes: 1, isLive: true, busId: 'bus-1' },
  { stopId: 'stop-2', routeId: 'green', minutes: 8, isLive: true, busId: 'bus-4' },
  { stopId: 'stop-3', routeId: 'red', minutes: 6, isLive: true, busId: 'bus-1' },
  { stopId: 'stop-4', routeId: 'red', minutes: 3, isLive: true, busId: 'bus-2' },
  { stopId: 'stop-5', routeId: 'yellow', minutes: 7, isLive: true, busId: 'bus-3' },
  { stopId: 'stop-6', routeId: 'yellow', minutes: 2, isLive: true, busId: 'bus-3' },
  { stopId: 'stop-7', routeId: 'green', minutes: 4, isLive: true, busId: 'bus-4' },
  { stopId: 'stop-8', routeId: 'green', minutes: 1, isLive: true, busId: 'bus-4' },
];

export const serviceAlerts: ServiceAlert[] = [
  {
    id: 'alert-1',
    routeIds: ['red'],
    title: 'Slight Delay on Red Line',
    description: 'Medical Campus stop experiencing 5-minute delays due to traffic.',
    severity: 'warning',
    timestamp: '2025-10-25T10:30:00',
  },
  {
    id: 'alert-2',
    routeIds: ['yellow', 'green'],
    title: 'Service Running Normally',
    description: 'All buses on schedule.',
    severity: 'info',
    timestamp: '2025-10-25T09:00:00',
  },
];
